##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Ann Horner Needlepoint Collection 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Needlepoint Hobby of a Memphis Woman
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Ann Kathryn Higginbotham Horner Needlepoint Collection (c.1960s-2000s) includes a range of materials accumulated by her granddaughter, May Higginbotham, which document Ann Horner’s needlepoint practice and projects. The collection includes patterns, needlepoint kits, unfinished projects, embroidery tools and supplies, an oral history, and finished needlepoint projects. Ann Horner (nee Oliver) was born on October 24, 1945 in Oakland, California to Preston and Barbara Oliver. The Olivers moved to Memphis, Tennessee when Ann was 18 months old. The family briefly lived in Dallas, Texas for two years when Ann was an early teen. They moved back to Memphis after this, where Ann has resided since. She attended White Station High School in East Memphis and then attended finishing school at Stephens College in Columbia, Missouri for a year before marrying her first husband, Wayne Higginbotham, in 1966. Ann had two sons, Michael and Robert, who also reside in Memphis. Ann attributes her needlepoint hobby to her lifelong friend Pamela; the two were neighbors and created fiber crafts, including also knitting and cross stitch, together starting when they were young mothers. Ann also has five grandchildren, with whom she shares her needlepoint hobby. For Ann Horner, needlepoint was an outlet for personal expression and a hobby that added deeper meaning to her life. Many of the items in the collections showcase her whimsical style and taste. She spent time needlepointing items that decorated her home, she connected with her friends over fiber craft, and made items to gift to her loved ones."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: collection-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
